### ISSUE TITLE
stack trace on FreeBSD 10.1 during `jetpack init`

### ISSUE THREAD

**Issue by dch** [3ofcoins/jetpack#10]
git checkout today using 9c88b57d8e502c8706b50229120257493398486c crashes during `jetpack init`.

- zroot/var/jetpack created already, see https://dpaste.de/t1Xa for dataset setup (not very exciting).
- FreeBSD 10.1-RELEASE-p10 (GENERIC) #0: Wed May 13 06:54:13 UTC 2015
- go version go1.4.2 freebsd/amd64 (pkg)

```
wintermute# jetpack init
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x488385]

goroutine 1 [running]:
lib/jetpack.(*Host).Initialize(0x0, 0x0, 0x0)
	/usr/home/dch/src/jetpack/src/lib/jetpack/host.go:108 +0x45
lib/jetpack.*Host.Initialize·fm(0x0, 0x0)
	/usr/home/dch/src/jetpack/src/bin/jetpack/host.go:10 +0x39
main.func·002(0xc20800a010, 0x0, 0x0, 0x0, 0x0)
	/usr/home/dch/src/jetpack/src/bin/jetpack/command.go:81 +0x38
main.(*Command).Run(0xc2080823c0, 0xc20800a010, 0x0, 0x0, 0x0, 0x0)
	/usr/home/dch/src/jetpack/src/bin/jetpack/command.go:69 +0xe1
main.main()
	/usr/home/dch/src/jetpack/src/bin/jetpack/main.go:47 +0x274
wintermute#
```

**Comment by mpasternacki** [comment]
Should be fixed now. Please note that `jetpack init` tries to create the datasets, based on settings in `jetpack.conf`, so if the dataset already exists, it may still fail because of that.

**Comment by dch** [comment]
🚀 works for me thanks!
