### ISSUE TITLE
Compatible containers?

### ISSUE THREAD

**Issue by dominikwille** [3ofcoins/jetpack#2]
Is it possible to execute the same containers with different implementations of the App Container Specification? Or can I run a Rocket Container with JetPack?

**Comment by mpasternacki** [comment]
I'm afraid it's not possible: while ACI format is the same, the operating system and architecture is different. Even though FreeBSD can run Linux binaries, it is restricted to 32-bit x86 architecture (and 32-bit Linux images do work), and Rocket is 64-bit only. It may be somewhat compatible (as much as FreeBSD's Linux emulation covers required system calls) if Rocket or other Linux implementation supports 32-bit x86 images.

Depending on how the tooling around the spec evolves, it may be possible at some point to use the same configuration files or scripts to build container images for Linux/Rocket and for FreeBSD/Jetpack.
