### ISSUE TITLE
pods running, but cant console

### ISSUE THREAD

**Issue by outbackdingo** [3ofcoins/jetpack#4]
This does work on run command, however fails to console later
jetpack pod 43986964-d255-47b0-9086-56780846b8d9 run
jetpack:43986964-d255-47b0-9086-56780846b8d9: run command: /sbin/ifconfig lo1 inet 172.23.0.2 netmask 255.255.255.255 alias
jetpack:43986964-d255-47b0-9086-56780846b8d9: run command: /sbin/mount -t devfs -o ruleset=4 . /var/jetpack/pods/43986964-d255-47b0-9086-56780846b8d9/rootfs/0/dev
jetpack:43986964-d255-47b0-9086-56780846b8d9: jail_set(JAIL_CREATE) name=jetpack:43986964-d255-47b0-9086-56780846b8d9 host.hostname=43986964-d255-47b0-9086-56780846b8d9 host.hostuuid=43986964-d255-47b0-9086-56780846b8d9 ip4.addr=172.23.0.2 path=/var/jetpack/pods/43986964-d255-47b0-9086-56780846b8d9/rootfs persist=true
jetpack:43986964-d255-47b0-9086-56780846b8d9: created
FreeBSD ?.?.?  (UNKNOWN)

Welcome to FreeBSD!

then if i CTRL-D im back in my host OS

jetpack pod list
UUID                                  STATUS   IP          APPS
43986964-d255-47b0-9086-56780846b8d9  running  172.23.0.2  freebsd-base
root@xoa:~/jetpack/images/freebsd-base # jetpack pod 43986964-d255-47b0-9086-56780846b8d9 console
panic: open /etc/passwd: no such file or directory

goroutine 1 [running]:
main.main()
        /root/jetpack/stage2/main.go:59 +0x4bd

goroutine 2 [runnable]:
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:90
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
        /usr/local/go/src/runtime/mgc0.go:82
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
        /usr/local/go/src/runtime/malloc.go:712
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
run.Command[/root/jetpack/bin/stage2 -jid 4 -chroot / -user root -group  -name  /usr/bin/login -fp root]: exit status 2

**Comment by mpasternacki** [comment]
This seems also related to the multi-app pod code. Looking into it.
