### ISSUE TITLE
debootstrap for hamm?

### ISSUE THREAD

**Issue by mcandre** [3ofcoins/jetpack#9]
I see hamm listed in https://github.com/3ofcoins/jetpack/blob/master/images/debootstrap/debootstrap.sh , but when I try to debootstrap it, I get `/usr/lib/debootstrap/scripts/hamm`.

**Comment by mpasternacki** [comment]
Hamm is no longer maintained, and has been archived. I have left codenames of all Debian & Ubuntu releases in the script, pointing at main site of Debian/Ubuntu, and hamm has been moved to the archive. I've fixed the script to use archive.debian.org for the old releases, it should fix the problem. If it doesn't, then I'll remove the old releases from the script altogether.

**Comment by mpasternacki** [comment]
Looks like hamm and slinky are not supported by the debootstrap script. Removed these codenames from debootstrap.sh. Thanks for pointing it out!
